// Code generated by go-swagger; DO NOT EDIT.

package segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/csmarchbanks/stravaql/strava/model"
)

// GetSegmentByIDReader is a Reader for the GetSegmentByID structure.
type GetSegmentByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSegmentByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSegmentByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetSegmentByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetSegmentByIDOK creates a GetSegmentByIDOK with default headers values
func NewGetSegmentByIDOK() *GetSegmentByIDOK {
	return &GetSegmentByIDOK{}
}

/* GetSegmentByIDOK describes a response with status code 200, with default header values.

Representation of a segment.
*/
type GetSegmentByIDOK struct {
	Payload *model.DetailedSegment
}

func (o *GetSegmentByIDOK) Error() string {
	return fmt.Sprintf("[GET /segments/{id}][%d] getSegmentByIdOK  %+v", 200, o.Payload)
}
func (o *GetSegmentByIDOK) GetPayload() *model.DetailedSegment {
	return o.Payload
}

func (o *GetSegmentByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DetailedSegment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSegmentByIDDefault creates a GetSegmentByIDDefault with default headers values
func NewGetSegmentByIDDefault(code int) *GetSegmentByIDDefault {
	return &GetSegmentByIDDefault{
		_statusCode: code,
	}
}

/* GetSegmentByIDDefault describes a response with status code -1, with default header values.

Unexpected error.
*/
type GetSegmentByIDDefault struct {
	_statusCode int

	Payload *model.Fault
}

// Code gets the status code for the get segment by Id default response
func (o *GetSegmentByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetSegmentByIDDefault) Error() string {
	return fmt.Sprintf("[GET /segments/{id}][%d] getSegmentById default  %+v", o._statusCode, o.Payload)
}
func (o *GetSegmentByIDDefault) GetPayload() *model.Fault {
	return o.Payload
}

func (o *GetSegmentByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
