// Code generated by go-swagger; DO NOT EDIT.

package segments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/csmarchbanks/stravaql/strava/model"
)

// StarSegmentReader is a Reader for the StarSegment structure.
type StarSegmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StarSegmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStarSegmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStarSegmentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStarSegmentOK creates a StarSegmentOK with default headers values
func NewStarSegmentOK() *StarSegmentOK {
	return &StarSegmentOK{}
}

/* StarSegmentOK describes a response with status code 200, with default header values.

Representation of a segment.
*/
type StarSegmentOK struct {
	Payload *model.DetailedSegment
}

func (o *StarSegmentOK) Error() string {
	return fmt.Sprintf("[PUT /segments/{id}/starred][%d] starSegmentOK  %+v", 200, o.Payload)
}
func (o *StarSegmentOK) GetPayload() *model.DetailedSegment {
	return o.Payload
}

func (o *StarSegmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DetailedSegment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStarSegmentDefault creates a StarSegmentDefault with default headers values
func NewStarSegmentDefault(code int) *StarSegmentDefault {
	return &StarSegmentDefault{
		_statusCode: code,
	}
}

/* StarSegmentDefault describes a response with status code -1, with default header values.

Unexpected error.
*/
type StarSegmentDefault struct {
	_statusCode int

	Payload *model.Fault
}

// Code gets the status code for the star segment default response
func (o *StarSegmentDefault) Code() int {
	return o._statusCode
}

func (o *StarSegmentDefault) Error() string {
	return fmt.Sprintf("[PUT /segments/{id}/starred][%d] starSegment default  %+v", o._statusCode, o.Payload)
}
func (o *StarSegmentDefault) GetPayload() *model.Fault {
	return o.Payload
}

func (o *StarSegmentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
