// Code generated by go-swagger; DO NOT EDIT.

package streams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRouteStreamsParams creates a new GetRouteStreamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRouteStreamsParams() *GetRouteStreamsParams {
	return &GetRouteStreamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRouteStreamsParamsWithTimeout creates a new GetRouteStreamsParams object
// with the ability to set a timeout on a request.
func NewGetRouteStreamsParamsWithTimeout(timeout time.Duration) *GetRouteStreamsParams {
	return &GetRouteStreamsParams{
		timeout: timeout,
	}
}

// NewGetRouteStreamsParamsWithContext creates a new GetRouteStreamsParams object
// with the ability to set a context for a request.
func NewGetRouteStreamsParamsWithContext(ctx context.Context) *GetRouteStreamsParams {
	return &GetRouteStreamsParams{
		Context: ctx,
	}
}

// NewGetRouteStreamsParamsWithHTTPClient creates a new GetRouteStreamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRouteStreamsParamsWithHTTPClient(client *http.Client) *GetRouteStreamsParams {
	return &GetRouteStreamsParams{
		HTTPClient: client,
	}
}

/* GetRouteStreamsParams contains all the parameters to send to the API endpoint
   for the get route streams operation.

   Typically these are written to a http.Request.
*/
type GetRouteStreamsParams struct {

	/* ID.

	   The identifier of the route.

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get route streams params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRouteStreamsParams) WithDefaults() *GetRouteStreamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get route streams params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRouteStreamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get route streams params
func (o *GetRouteStreamsParams) WithTimeout(timeout time.Duration) *GetRouteStreamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get route streams params
func (o *GetRouteStreamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get route streams params
func (o *GetRouteStreamsParams) WithContext(ctx context.Context) *GetRouteStreamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get route streams params
func (o *GetRouteStreamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get route streams params
func (o *GetRouteStreamsParams) WithHTTPClient(client *http.Client) *GetRouteStreamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get route streams params
func (o *GetRouteStreamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get route streams params
func (o *GetRouteStreamsParams) WithID(id int64) *GetRouteStreamsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get route streams params
func (o *GetRouteStreamsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRouteStreamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
