// Code generated by go-swagger; DO NOT EDIT.

package uploads

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUploadByIDParams creates a new GetUploadByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUploadByIDParams() *GetUploadByIDParams {
	return &GetUploadByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUploadByIDParamsWithTimeout creates a new GetUploadByIDParams object
// with the ability to set a timeout on a request.
func NewGetUploadByIDParamsWithTimeout(timeout time.Duration) *GetUploadByIDParams {
	return &GetUploadByIDParams{
		timeout: timeout,
	}
}

// NewGetUploadByIDParamsWithContext creates a new GetUploadByIDParams object
// with the ability to set a context for a request.
func NewGetUploadByIDParamsWithContext(ctx context.Context) *GetUploadByIDParams {
	return &GetUploadByIDParams{
		Context: ctx,
	}
}

// NewGetUploadByIDParamsWithHTTPClient creates a new GetUploadByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUploadByIDParamsWithHTTPClient(client *http.Client) *GetUploadByIDParams {
	return &GetUploadByIDParams{
		HTTPClient: client,
	}
}

/* GetUploadByIDParams contains all the parameters to send to the API endpoint
   for the get upload by Id operation.

   Typically these are written to a http.Request.
*/
type GetUploadByIDParams struct {

	/* UploadID.

	   The identifier of the upload.

	   Format: int64
	*/
	UploadID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get upload by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUploadByIDParams) WithDefaults() *GetUploadByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get upload by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUploadByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get upload by Id params
func (o *GetUploadByIDParams) WithTimeout(timeout time.Duration) *GetUploadByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get upload by Id params
func (o *GetUploadByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get upload by Id params
func (o *GetUploadByIDParams) WithContext(ctx context.Context) *GetUploadByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get upload by Id params
func (o *GetUploadByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get upload by Id params
func (o *GetUploadByIDParams) WithHTTPClient(client *http.Client) *GetUploadByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get upload by Id params
func (o *GetUploadByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUploadID adds the uploadID to the get upload by Id params
func (o *GetUploadByIDParams) WithUploadID(uploadID int64) *GetUploadByIDParams {
	o.SetUploadID(uploadID)
	return o
}

// SetUploadID adds the uploadId to the get upload by Id params
func (o *GetUploadByIDParams) SetUploadID(uploadID int64) {
	o.UploadID = uploadID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUploadByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uploadId
	if err := r.SetPathParam("uploadId", swag.FormatInt64(o.UploadID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
