// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetaClub meta club
//
// swagger:model metaClub
type MetaClub struct {

	// The club's unique identifier.
	ID int64 `json:"id,omitempty"`

	// The club's name.
	Name string `json:"name,omitempty"`

	// Resource state, indicates level of detail. Possible values: 1 -> "meta", 2 -> "summary", 3 -> "detail"
	ResourceState int64 `json:"resource_state,omitempty"`
}

// Validate validates this meta club
func (m *MetaClub) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this meta club based on context it is used
func (m *MetaClub) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetaClub) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetaClub) UnmarshalBinary(b []byte) error {
	var res MetaClub
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
