// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetaAthlete meta athlete
//
// swagger:model metaAthlete
type MetaAthlete struct {

	// The unique identifier of the athlete
	ID int64 `json:"id,omitempty"`
}

// Validate validates this meta athlete
func (m *MetaAthlete) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this meta athlete based on context it is used
func (m *MetaAthlete) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetaAthlete) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetaAthlete) UnmarshalBinary(b []byte) error {
	var res MetaAthlete
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
