// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PolylineMap polyline map
//
// swagger:model polylineMap
type PolylineMap struct {

	// The identifier of the map
	ID string `json:"id,omitempty"`

	// The polyline of the map, only returned on detailed representation of an object
	Polyline string `json:"polyline,omitempty"`

	// The summary polyline of the map
	SummaryPolyline string `json:"summary_polyline,omitempty"`
}

// Validate validates this polyline map
func (m *PolylineMap) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this polyline map based on context it is used
func (m *PolylineMap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PolylineMap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolylineMap) UnmarshalBinary(b []byte) error {
	var res PolylineMap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
