// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// SportType An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
//
// swagger:model sportType
type SportType string

func NewSportType(value SportType) *SportType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated SportType.
func (m SportType) Pointer() *SportType {
	return &m
}

const (

	// SportTypeAlpineSki captures enum value "AlpineSki"
	SportTypeAlpineSki SportType = "AlpineSki"

	// SportTypeBackcountrySki captures enum value "BackcountrySki"
	SportTypeBackcountrySki SportType = "BackcountrySki"

	// SportTypeCanoeing captures enum value "Canoeing"
	SportTypeCanoeing SportType = "Canoeing"

	// SportTypeCrossfit captures enum value "Crossfit"
	SportTypeCrossfit SportType = "Crossfit"

	// SportTypeEBikeRide captures enum value "EBikeRide"
	SportTypeEBikeRide SportType = "EBikeRide"

	// SportTypeElliptical captures enum value "Elliptical"
	SportTypeElliptical SportType = "Elliptical"

	// SportTypeEMountainBikeRide captures enum value "EMountainBikeRide"
	SportTypeEMountainBikeRide SportType = "EMountainBikeRide"

	// SportTypeGolf captures enum value "Golf"
	SportTypeGolf SportType = "Golf"

	// SportTypeGravelRide captures enum value "GravelRide"
	SportTypeGravelRide SportType = "GravelRide"

	// SportTypeHandcycle captures enum value "Handcycle"
	SportTypeHandcycle SportType = "Handcycle"

	// SportTypeHike captures enum value "Hike"
	SportTypeHike SportType = "Hike"

	// SportTypeIceSkate captures enum value "IceSkate"
	SportTypeIceSkate SportType = "IceSkate"

	// SportTypeInlineSkate captures enum value "InlineSkate"
	SportTypeInlineSkate SportType = "InlineSkate"

	// SportTypeKayaking captures enum value "Kayaking"
	SportTypeKayaking SportType = "Kayaking"

	// SportTypeKitesurf captures enum value "Kitesurf"
	SportTypeKitesurf SportType = "Kitesurf"

	// SportTypeMountainBikeRide captures enum value "MountainBikeRide"
	SportTypeMountainBikeRide SportType = "MountainBikeRide"

	// SportTypeNordicSki captures enum value "NordicSki"
	SportTypeNordicSki SportType = "NordicSki"

	// SportTypeRide captures enum value "Ride"
	SportTypeRide SportType = "Ride"

	// SportTypeRockClimbing captures enum value "RockClimbing"
	SportTypeRockClimbing SportType = "RockClimbing"

	// SportTypeRollerSki captures enum value "RollerSki"
	SportTypeRollerSki SportType = "RollerSki"

	// SportTypeRowing captures enum value "Rowing"
	SportTypeRowing SportType = "Rowing"

	// SportTypeRun captures enum value "Run"
	SportTypeRun SportType = "Run"

	// SportTypeSail captures enum value "Sail"
	SportTypeSail SportType = "Sail"

	// SportTypeSkateboard captures enum value "Skateboard"
	SportTypeSkateboard SportType = "Skateboard"

	// SportTypeSnowboard captures enum value "Snowboard"
	SportTypeSnowboard SportType = "Snowboard"

	// SportTypeSnowshoe captures enum value "Snowshoe"
	SportTypeSnowshoe SportType = "Snowshoe"

	// SportTypeSoccer captures enum value "Soccer"
	SportTypeSoccer SportType = "Soccer"

	// SportTypeStairStepper captures enum value "StairStepper"
	SportTypeStairStepper SportType = "StairStepper"

	// SportTypeStandUpPaddling captures enum value "StandUpPaddling"
	SportTypeStandUpPaddling SportType = "StandUpPaddling"

	// SportTypeSurfing captures enum value "Surfing"
	SportTypeSurfing SportType = "Surfing"

	// SportTypeSwim captures enum value "Swim"
	SportTypeSwim SportType = "Swim"

	// SportTypeTrailRun captures enum value "TrailRun"
	SportTypeTrailRun SportType = "TrailRun"

	// SportTypeVelomobile captures enum value "Velomobile"
	SportTypeVelomobile SportType = "Velomobile"

	// SportTypeVirtualRide captures enum value "VirtualRide"
	SportTypeVirtualRide SportType = "VirtualRide"

	// SportTypeVirtualRun captures enum value "VirtualRun"
	SportTypeVirtualRun SportType = "VirtualRun"

	// SportTypeWalk captures enum value "Walk"
	SportTypeWalk SportType = "Walk"

	// SportTypeWeightTraining captures enum value "WeightTraining"
	SportTypeWeightTraining SportType = "WeightTraining"

	// SportTypeWheelchair captures enum value "Wheelchair"
	SportTypeWheelchair SportType = "Wheelchair"

	// SportTypeWindsurf captures enum value "Windsurf"
	SportTypeWindsurf SportType = "Windsurf"

	// SportTypeWorkout captures enum value "Workout"
	SportTypeWorkout SportType = "Workout"

	// SportTypeYoga captures enum value "Yoga"
	SportTypeYoga SportType = "Yoga"
)

// for schema
var sportTypeEnum []interface{}

func init() {
	var res []SportType
	if err := json.Unmarshal([]byte(`["AlpineSki","BackcountrySki","Canoeing","Crossfit","EBikeRide","Elliptical","EMountainBikeRide","Golf","GravelRide","Handcycle","Hike","IceSkate","InlineSkate","Kayaking","Kitesurf","MountainBikeRide","NordicSki","Ride","RockClimbing","RollerSki","Rowing","Run","Sail","Skateboard","Snowboard","Snowshoe","Soccer","StairStepper","StandUpPaddling","Surfing","Swim","TrailRun","Velomobile","VirtualRide","VirtualRun","Walk","WeightTraining","Wheelchair","Windsurf","Workout","Yoga"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sportTypeEnum = append(sportTypeEnum, v)
	}
}

func (m SportType) validateSportTypeEnum(path, location string, value SportType) error {
	if err := validate.EnumCase(path, location, value, sportTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this sport type
func (m SportType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateSportTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this sport type based on context it is used
func (m SportType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
