// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SummaryGear summary gear
//
// swagger:model summaryGear
type SummaryGear struct {

	// The distance logged with this gear.
	Distance float32 `json:"distance,omitempty"`

	// The gear's unique identifier.
	ID string `json:"id,omitempty"`

	// The gear's name.
	Name string `json:"name,omitempty"`

	// Whether this gear's is the owner's default one.
	Primary bool `json:"primary,omitempty"`

	// Resource state, indicates level of detail. Possible values: 2 -> "summary", 3 -> "detail"
	ResourceState int64 `json:"resource_state,omitempty"`
}

// Validate validates this summary gear
func (m *SummaryGear) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this summary gear based on context it is used
func (m *SummaryGear) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SummaryGear) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SummaryGear) UnmarshalBinary(b []byte) error {
	var res SummaryGear
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
