// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SummarySegmentEffort summary segment effort
//
// swagger:model summarySegmentEffort
type SummarySegmentEffort struct {

	// The unique identifier of the activity related to this effort
	ActivityID int64 `json:"activity_id,omitempty"`

	// The effort's distance in meters
	Distance float32 `json:"distance,omitempty"`

	// The effort's elapsed time
	ElapsedTime int64 `json:"elapsed_time,omitempty"`

	// The unique identifier of this effort
	ID int64 `json:"id,omitempty"`

	// Whether this effort is the current best on the leaderboard
	IsKom bool `json:"is_kom,omitempty"`

	// The time at which the effort was started.
	// Format: date-time
	StartDate strfmt.DateTime `json:"start_date,omitempty"`

	// The time at which the effort was started in the local timezone.
	// Format: date-time
	StartDateLocal strfmt.DateTime `json:"start_date_local,omitempty"`
}

// Validate validates this summary segment effort
func (m *SummarySegmentEffort) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStartDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartDateLocal(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SummarySegmentEffort) validateStartDate(formats strfmt.Registry) error {
	if swag.IsZero(m.StartDate) { // not required
		return nil
	}

	if err := validate.FormatOf("start_date", "body", "date-time", m.StartDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SummarySegmentEffort) validateStartDateLocal(formats strfmt.Registry) error {
	if swag.IsZero(m.StartDateLocal) { // not required
		return nil
	}

	if err := validate.FormatOf("start_date_local", "body", "date-time", m.StartDateLocal.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this summary segment effort based on context it is used
func (m *SummarySegmentEffort) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SummarySegmentEffort) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SummarySegmentEffort) UnmarshalBinary(b []byte) error {
	var res SummarySegmentEffort
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
