// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Upload upload
//
// swagger:model upload
type Upload struct {

	// The identifier of the activity this upload resulted into
	ActivityID int64 `json:"activity_id,omitempty"`

	// The error associated with this upload
	Error string `json:"error,omitempty"`

	// The external identifier of the upload
	ExternalID string `json:"external_id,omitempty"`

	// The unique identifier of the upload
	ID int64 `json:"id,omitempty"`

	// The unique identifier of the upload in string format
	IDStr string `json:"id_str,omitempty"`

	// The status of this upload
	Status string `json:"status,omitempty"`
}

// Validate validates this upload
func (m *Upload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upload based on context it is used
func (m *Upload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Upload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Upload) UnmarshalBinary(b []byte) error {
	var res Upload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
