// Code generated by go-swagger; DO NOT EDIT.

package activities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/csmarchbanks/stravaql/strava/model"
)

// GetLoggedInAthleteActivitiesReader is a Reader for the GetLoggedInAthleteActivities structure.
type GetLoggedInAthleteActivitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLoggedInAthleteActivitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLoggedInAthleteActivitiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetLoggedInAthleteActivitiesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetLoggedInAthleteActivitiesOK creates a GetLoggedInAthleteActivitiesOK with default headers values
func NewGetLoggedInAthleteActivitiesOK() *GetLoggedInAthleteActivitiesOK {
	return &GetLoggedInAthleteActivitiesOK{}
}

/* GetLoggedInAthleteActivitiesOK describes a response with status code 200, with default header values.

The authenticated athlete's activities
*/
type GetLoggedInAthleteActivitiesOK struct {
	Payload []*model.SummaryActivity
}

func (o *GetLoggedInAthleteActivitiesOK) Error() string {
	return fmt.Sprintf("[GET /athlete/activities][%d] getLoggedInAthleteActivitiesOK  %+v", 200, o.Payload)
}
func (o *GetLoggedInAthleteActivitiesOK) GetPayload() []*model.SummaryActivity {
	return o.Payload
}

func (o *GetLoggedInAthleteActivitiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLoggedInAthleteActivitiesDefault creates a GetLoggedInAthleteActivitiesDefault with default headers values
func NewGetLoggedInAthleteActivitiesDefault(code int) *GetLoggedInAthleteActivitiesDefault {
	return &GetLoggedInAthleteActivitiesDefault{
		_statusCode: code,
	}
}

/* GetLoggedInAthleteActivitiesDefault describes a response with status code -1, with default header values.

Unexpected error.
*/
type GetLoggedInAthleteActivitiesDefault struct {
	_statusCode int

	Payload *model.Fault
}

// Code gets the status code for the get logged in athlete activities default response
func (o *GetLoggedInAthleteActivitiesDefault) Code() int {
	return o._statusCode
}

func (o *GetLoggedInAthleteActivitiesDefault) Error() string {
	return fmt.Sprintf("[GET /athlete/activities][%d] getLoggedInAthleteActivities default  %+v", o._statusCode, o.Payload)
}
func (o *GetLoggedInAthleteActivitiesDefault) GetPayload() *model.Fault {
	return o.Payload
}

func (o *GetLoggedInAthleteActivitiesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
