// Code generated by go-swagger; DO NOT EDIT.

package activities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/csmarchbanks/stravaql/strava/model"
)

// NewUpdateActivityByIDParams creates a new UpdateActivityByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateActivityByIDParams() *UpdateActivityByIDParams {
	return &UpdateActivityByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateActivityByIDParamsWithTimeout creates a new UpdateActivityByIDParams object
// with the ability to set a timeout on a request.
func NewUpdateActivityByIDParamsWithTimeout(timeout time.Duration) *UpdateActivityByIDParams {
	return &UpdateActivityByIDParams{
		timeout: timeout,
	}
}

// NewUpdateActivityByIDParamsWithContext creates a new UpdateActivityByIDParams object
// with the ability to set a context for a request.
func NewUpdateActivityByIDParamsWithContext(ctx context.Context) *UpdateActivityByIDParams {
	return &UpdateActivityByIDParams{
		Context: ctx,
	}
}

// NewUpdateActivityByIDParamsWithHTTPClient creates a new UpdateActivityByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateActivityByIDParamsWithHTTPClient(client *http.Client) *UpdateActivityByIDParams {
	return &UpdateActivityByIDParams{
		HTTPClient: client,
	}
}

/* UpdateActivityByIDParams contains all the parameters to send to the API endpoint
   for the update activity by Id operation.

   Typically these are written to a http.Request.
*/
type UpdateActivityByIDParams struct {

	// Body.
	Body *model.UpdatableActivity

	/* ID.

	   The identifier of the activity.

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update activity by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateActivityByIDParams) WithDefaults() *UpdateActivityByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update activity by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateActivityByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update activity by Id params
func (o *UpdateActivityByIDParams) WithTimeout(timeout time.Duration) *UpdateActivityByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update activity by Id params
func (o *UpdateActivityByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update activity by Id params
func (o *UpdateActivityByIDParams) WithContext(ctx context.Context) *UpdateActivityByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update activity by Id params
func (o *UpdateActivityByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update activity by Id params
func (o *UpdateActivityByIDParams) WithHTTPClient(client *http.Client) *UpdateActivityByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update activity by Id params
func (o *UpdateActivityByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update activity by Id params
func (o *UpdateActivityByIDParams) WithBody(body *model.UpdatableActivity) *UpdateActivityByIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update activity by Id params
func (o *UpdateActivityByIDParams) SetBody(body *model.UpdatableActivity) {
	o.Body = body
}

// WithID adds the id to the update activity by Id params
func (o *UpdateActivityByIDParams) WithID(id int64) *UpdateActivityByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update activity by Id params
func (o *UpdateActivityByIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateActivityByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
