// Code generated by go-swagger; DO NOT EDIT.

package clubs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/csmarchbanks/stravaql/strava/model"
)

// GetClubByIDReader is a Reader for the GetClubByID structure.
type GetClubByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClubByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClubByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetClubByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetClubByIDOK creates a GetClubByIDOK with default headers values
func NewGetClubByIDOK() *GetClubByIDOK {
	return &GetClubByIDOK{}
}

/* GetClubByIDOK describes a response with status code 200, with default header values.

The detailed representation of a club.
*/
type GetClubByIDOK struct {
	Payload *model.DetailedClub
}

func (o *GetClubByIDOK) Error() string {
	return fmt.Sprintf("[GET /clubs/{id}][%d] getClubByIdOK  %+v", 200, o.Payload)
}
func (o *GetClubByIDOK) GetPayload() *model.DetailedClub {
	return o.Payload
}

func (o *GetClubByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DetailedClub)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClubByIDDefault creates a GetClubByIDDefault with default headers values
func NewGetClubByIDDefault(code int) *GetClubByIDDefault {
	return &GetClubByIDDefault{
		_statusCode: code,
	}
}

/* GetClubByIDDefault describes a response with status code -1, with default header values.

Unexpected error.
*/
type GetClubByIDDefault struct {
	_statusCode int

	Payload *model.Fault
}

// Code gets the status code for the get club by Id default response
func (o *GetClubByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetClubByIDDefault) Error() string {
	return fmt.Sprintf("[GET /clubs/{id}][%d] getClubById default  %+v", o._statusCode, o.Payload)
}
func (o *GetClubByIDDefault) GetPayload() *model.Fault {
	return o.Payload
}

func (o *GetClubByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
