// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRouteAsTCXParams creates a new GetRouteAsTCXParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRouteAsTCXParams() *GetRouteAsTCXParams {
	return &GetRouteAsTCXParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRouteAsTCXParamsWithTimeout creates a new GetRouteAsTCXParams object
// with the ability to set a timeout on a request.
func NewGetRouteAsTCXParamsWithTimeout(timeout time.Duration) *GetRouteAsTCXParams {
	return &GetRouteAsTCXParams{
		timeout: timeout,
	}
}

// NewGetRouteAsTCXParamsWithContext creates a new GetRouteAsTCXParams object
// with the ability to set a context for a request.
func NewGetRouteAsTCXParamsWithContext(ctx context.Context) *GetRouteAsTCXParams {
	return &GetRouteAsTCXParams{
		Context: ctx,
	}
}

// NewGetRouteAsTCXParamsWithHTTPClient creates a new GetRouteAsTCXParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRouteAsTCXParamsWithHTTPClient(client *http.Client) *GetRouteAsTCXParams {
	return &GetRouteAsTCXParams{
		HTTPClient: client,
	}
}

/* GetRouteAsTCXParams contains all the parameters to send to the API endpoint
   for the get route as t c x operation.

   Typically these are written to a http.Request.
*/
type GetRouteAsTCXParams struct {

	/* ID.

	   The identifier of the route.

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get route as t c x params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRouteAsTCXParams) WithDefaults() *GetRouteAsTCXParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get route as t c x params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRouteAsTCXParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get route as t c x params
func (o *GetRouteAsTCXParams) WithTimeout(timeout time.Duration) *GetRouteAsTCXParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get route as t c x params
func (o *GetRouteAsTCXParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get route as t c x params
func (o *GetRouteAsTCXParams) WithContext(ctx context.Context) *GetRouteAsTCXParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get route as t c x params
func (o *GetRouteAsTCXParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get route as t c x params
func (o *GetRouteAsTCXParams) WithHTTPClient(client *http.Client) *GetRouteAsTCXParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get route as t c x params
func (o *GetRouteAsTCXParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get route as t c x params
func (o *GetRouteAsTCXParams) WithID(id int64) *GetRouteAsTCXParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get route as t c x params
func (o *GetRouteAsTCXParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRouteAsTCXParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
