// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRoutesByAthleteIDParams creates a new GetRoutesByAthleteIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRoutesByAthleteIDParams() *GetRoutesByAthleteIDParams {
	return &GetRoutesByAthleteIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRoutesByAthleteIDParamsWithTimeout creates a new GetRoutesByAthleteIDParams object
// with the ability to set a timeout on a request.
func NewGetRoutesByAthleteIDParamsWithTimeout(timeout time.Duration) *GetRoutesByAthleteIDParams {
	return &GetRoutesByAthleteIDParams{
		timeout: timeout,
	}
}

// NewGetRoutesByAthleteIDParamsWithContext creates a new GetRoutesByAthleteIDParams object
// with the ability to set a context for a request.
func NewGetRoutesByAthleteIDParamsWithContext(ctx context.Context) *GetRoutesByAthleteIDParams {
	return &GetRoutesByAthleteIDParams{
		Context: ctx,
	}
}

// NewGetRoutesByAthleteIDParamsWithHTTPClient creates a new GetRoutesByAthleteIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRoutesByAthleteIDParamsWithHTTPClient(client *http.Client) *GetRoutesByAthleteIDParams {
	return &GetRoutesByAthleteIDParams{
		HTTPClient: client,
	}
}

/* GetRoutesByAthleteIDParams contains all the parameters to send to the API endpoint
   for the get routes by athlete Id operation.

   Typically these are written to a http.Request.
*/
type GetRoutesByAthleteIDParams struct {

	/* Page.

	   Page number. Defaults to 1.
	*/
	Page *int64

	/* PerPage.

	   Number of items per page. Defaults to 30.

	   Default: 30
	*/
	PerPage *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get routes by athlete Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoutesByAthleteIDParams) WithDefaults() *GetRoutesByAthleteIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get routes by athlete Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRoutesByAthleteIDParams) SetDefaults() {
	var (
		perPageDefault = int64(30)
	)

	val := GetRoutesByAthleteIDParams{
		PerPage: &perPageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) WithTimeout(timeout time.Duration) *GetRoutesByAthleteIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) WithContext(ctx context.Context) *GetRoutesByAthleteIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) WithHTTPClient(client *http.Client) *GetRoutesByAthleteIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) WithPage(page *int64) *GetRoutesByAthleteIDParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) SetPage(page *int64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) WithPerPage(perPage *int64) *GetRoutesByAthleteIDParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get routes by athlete Id params
func (o *GetRoutesByAthleteIDParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetRoutesByAthleteIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage int64

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {

			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
