// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetRouteAsGPXParams creates a new GetRouteAsGPXParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRouteAsGPXParams() *GetRouteAsGPXParams {
	return &GetRouteAsGPXParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRouteAsGPXParamsWithTimeout creates a new GetRouteAsGPXParams object
// with the ability to set a timeout on a request.
func NewGetRouteAsGPXParamsWithTimeout(timeout time.Duration) *GetRouteAsGPXParams {
	return &GetRouteAsGPXParams{
		timeout: timeout,
	}
}

// NewGetRouteAsGPXParamsWithContext creates a new GetRouteAsGPXParams object
// with the ability to set a context for a request.
func NewGetRouteAsGPXParamsWithContext(ctx context.Context) *GetRouteAsGPXParams {
	return &GetRouteAsGPXParams{
		Context: ctx,
	}
}

// NewGetRouteAsGPXParamsWithHTTPClient creates a new GetRouteAsGPXParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRouteAsGPXParamsWithHTTPClient(client *http.Client) *GetRouteAsGPXParams {
	return &GetRouteAsGPXParams{
		HTTPClient: client,
	}
}

/* GetRouteAsGPXParams contains all the parameters to send to the API endpoint
   for the get route as g p x operation.

   Typically these are written to a http.Request.
*/
type GetRouteAsGPXParams struct {

	/* ID.

	   The identifier of the route.

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get route as g p x params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRouteAsGPXParams) WithDefaults() *GetRouteAsGPXParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get route as g p x params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRouteAsGPXParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get route as g p x params
func (o *GetRouteAsGPXParams) WithTimeout(timeout time.Duration) *GetRouteAsGPXParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get route as g p x params
func (o *GetRouteAsGPXParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get route as g p x params
func (o *GetRouteAsGPXParams) WithContext(ctx context.Context) *GetRouteAsGPXParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get route as g p x params
func (o *GetRouteAsGPXParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get route as g p x params
func (o *GetRouteAsGPXParams) WithHTTPClient(client *http.Client) *GetRouteAsGPXParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get route as g p x params
func (o *GetRouteAsGPXParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get route as g p x params
func (o *GetRouteAsGPXParams) WithID(id int64) *GetRouteAsGPXParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get route as g p x params
func (o *GetRouteAsGPXParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRouteAsGPXParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
