// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/csmarchbanks/stravaql/strava/model"
)

// GetRoutesByAthleteIDReader is a Reader for the GetRoutesByAthleteID structure.
type GetRoutesByAthleteIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoutesByAthleteIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRoutesByAthleteIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetRoutesByAthleteIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetRoutesByAthleteIDOK creates a GetRoutesByAthleteIDOK with default headers values
func NewGetRoutesByAthleteIDOK() *GetRoutesByAthleteIDOK {
	return &GetRoutesByAthleteIDOK{}
}

/* GetRoutesByAthleteIDOK describes a response with status code 200, with default header values.

A representation of the route.
*/
type GetRoutesByAthleteIDOK struct {
	Payload []*model.Route
}

func (o *GetRoutesByAthleteIDOK) Error() string {
	return fmt.Sprintf("[GET /athletes/{id}/routes][%d] getRoutesByAthleteIdOK  %+v", 200, o.Payload)
}
func (o *GetRoutesByAthleteIDOK) GetPayload() []*model.Route {
	return o.Payload
}

func (o *GetRoutesByAthleteIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRoutesByAthleteIDDefault creates a GetRoutesByAthleteIDDefault with default headers values
func NewGetRoutesByAthleteIDDefault(code int) *GetRoutesByAthleteIDDefault {
	return &GetRoutesByAthleteIDDefault{
		_statusCode: code,
	}
}

/* GetRoutesByAthleteIDDefault describes a response with status code -1, with default header values.

Unexpected error.
*/
type GetRoutesByAthleteIDDefault struct {
	_statusCode int

	Payload *model.Fault
}

// Code gets the status code for the get routes by athlete Id default response
func (o *GetRoutesByAthleteIDDefault) Code() int {
	return o._statusCode
}

func (o *GetRoutesByAthleteIDDefault) Error() string {
	return fmt.Sprintf("[GET /athletes/{id}/routes][%d] getRoutesByAthleteId default  %+v", o._statusCode, o.Payload)
}
func (o *GetRoutesByAthleteIDDefault) GetPayload() *model.Fault {
	return o.Payload
}

func (o *GetRoutesByAthleteIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.Fault)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
