// Code generated by go-swagger; DO NOT EDIT.

package routes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new routes API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for routes API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetRouteAsGPX(params *GetRouteAsGPXParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRouteAsGPXOK, error)

	GetRouteAsTCX(params *GetRouteAsTCXParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRouteAsTCXOK, error)

	GetRouteByID(params *GetRouteByIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRouteByIDOK, error)

	GetRoutesByAthleteID(params *GetRoutesByAthleteIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRoutesByAthleteIDOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetRouteAsGPX exports route g p x

  Returns a GPX file of the route. Requires read_all scope for private routes.
*/
func (a *Client) GetRouteAsGPX(params *GetRouteAsGPXParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRouteAsGPXOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRouteAsGPXParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getRouteAsGPX",
		Method:             "GET",
		PathPattern:        "/routes/{id}/export_gpx",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRouteAsGPXReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRouteAsGPXOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetRouteAsGPXDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GetRouteAsTCX exports route t c x

  Returns a TCX file of the route. Requires read_all scope for private routes.
*/
func (a *Client) GetRouteAsTCX(params *GetRouteAsTCXParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRouteAsTCXOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRouteAsTCXParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getRouteAsTCX",
		Method:             "GET",
		PathPattern:        "/routes/{id}/export_tcx",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRouteAsTCXReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRouteAsTCXOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetRouteAsTCXDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GetRouteByID gets route

  Returns a route using its identifier. Requires read_all scope for private routes.
*/
func (a *Client) GetRouteByID(params *GetRouteByIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRouteByIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRouteByIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getRouteById",
		Method:             "GET",
		PathPattern:        "/routes/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRouteByIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRouteByIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetRouteByIDDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  GetRoutesByAthleteID lists athlete routes

  Returns a list of the routes created by the authenticated athlete. Private routes are filtered out unless requested by a token with read_all scope.
*/
func (a *Client) GetRoutesByAthleteID(params *GetRoutesByAthleteIDParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetRoutesByAthleteIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRoutesByAthleteIDParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "getRoutesByAthleteId",
		Method:             "GET",
		PathPattern:        "/athletes/{id}/routes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRoutesByAthleteIDReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRoutesByAthleteIDOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetRoutesByAthleteIDDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
